"""
Django settings for recos project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()
BASE_DIR = Path(__file__).resolve().parent.parent


SECRET_KEY = os.getenv('SECRET_KEY')

DEBUG = os.getenv('DEBUG', default=False)
if isinstance(DEBUG, bool):
    pass
else:
    DEBUG = DEBUG.lower() in ('true', '1', 't')
if DEBUG:
    CORS_ALLOWS_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS=[]

ALLOWED_HOSTS = []




INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'rest_framework.authtoken',
    'interviewConversation', 
    'job',
    'candidate',
    'api',
    'corsheaders',
    'users',
    'companies',
    "ai_reports",
    "interview",
    'drf_yasg',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "recos.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "recos.wsgi.application"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}



AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]




LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True




STATIC_URL = "static/"



DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


ODOO_API_ENCRYPTION_KEY = os.getenv('ODOO_API_ENCRYPTION_KEY')

if not ODOO_API_ENCRYPTION_KEY or len(ODOO_API_ENCRYPTION_KEY) < 16:
    raise ValueError("ODOO_API_ENCRYPTION_KEY must be set and be at least 16 characters long")

AUTH_USER_MODEL = 'users.Recruiter'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES':[
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES':[
        'rest_framework.permissions.IsAuthenticated',
    ],
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

AUTHENTICATION_BACKENDS = [
    'users.backends.EmailBackend', 
    'django.contrib.auth.backends.ModelBackend',
]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST')
if not EMAIL_HOST:
    raise ValueError("EMAIL_HOST environment variable is not set")

EMAIL_PORT = os.getenv('EMAIL_PORT')
if not EMAIL_PORT:
    raise ValueError("EMAIL_PORT environment variable is not set")
EMAIL_PORT = int(EMAIL_PORT)

EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 't')

EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
if not EMAIL_HOST_USER:
    raise ValueError("EMAIL_HOST_USER environment variable is not set")

EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
if not EMAIL_HOST_PASSWORD:
    raise ValueError("EMAIL_HOST_PASSWORD environment variable is not set")

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@recos.com')
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')
SITE_NAME = 'Recos'
PASSWORD_RESET_TIMEOUT = 3600


GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY')