# Generated by Django 5.2.6 on 2025-09-11 18:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidate", "0001_initial"),
        ("companies", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("phone_screen", "Phone Screen"),
                            ("technical", "Technical Interview"),
                            ("cultural", "Cultural Fit Interview"),
                            ("manager", "Hiring Manager Interview"),
                            ("panel", "Panel Interview"),
                            ("final", "Final Interview"),
                        ],
                        default="phone_screen",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("scheduled_at", models.DateTimeField()),
                (
                    "duration",
                    models.IntegerField(default=60, help_text="Duration in minutes"),
                ),
                ("interview_link", models.URLField(blank=True, null=True)),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Physical location if in-person",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("canceled", "Canceled"),
                            ("no_show", "No Show"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("pending", "Pending Review"),
                            ("recommended", "Recommended for Next Round"),
                            ("offer_extended", "Offer Extended"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True, null=True)),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Rating out of 5",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "google_event_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("google_calendar_link", models.URLField(blank=True, null=True)),
                ("send_calendar_invite", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_remote", models.BooleanField(default=True)),
                (
                    "required_preparation",
                    models.TextField(
                        blank=True,
                        help_text="Preparation materials for candidate",
                        null=True,
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="candidate.candidate",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_at"],
            },
        ),
    ]
