# Generated by Django 5.2.6 on 2025-09-14 07:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidate", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                ("interview_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("scheduled_at", models.DateTimeField()),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Duration in minutes",
                        validators=[
                            django.core.validators.MinValueValidator(15),
                            django.core.validators.MaxValueValidator(480),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("canceled", "Canceled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("interview_link", models.URLField(blank=True, null=True)),
                (
                    "google_event_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("google_calendar_link", models.URLField(blank=True, null=True)),
                ("send_calendar_invite", models.BooleanField(default=True)),
                (
                    "required_preparation",
                    models.TextField(
                        blank=True,
                        help_text="Preparation materials for candidate",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="candidate.candidate",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_at"],
            },
        ),
    ]
