# Generated by Django 5.2.6 on 2025-09-11 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("interview", "0001_initial"),
        ("job", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="interview_team",
            field=models.ManyToManyField(
                blank=True,
                help_text="Additional interviewers",
                related_name="team_interviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="interview",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interviews",
                to="job.job",
            ),
        ),
        migrations.AddField(
            model_name="interview",
            name="recruiter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="interview",
            index=models.Index(
                fields=["candidate", "scheduled_at"],
                name="interview_i_candida_6e9710_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interview",
            index=models.Index(
                fields=["recruiter", "scheduled_at"],
                name="interview_i_recruit_07c270_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interview",
            index=models.Index(
                fields=["company", "scheduled_at"],
                name="interview_i_company_3a464e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interview",
            index=models.Index(
                fields=["status", "scheduled_at"], name="interview_i_status_c2c60a_idx"
            ),
        ),
    ]
