# Generated by Django 4.2.24 on 2025-09-12 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interview", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="recruiter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="interview",
            index=models.Index(
                fields=["candidate", "scheduled_at"],
                name="interview_i_candida_6e9710_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interview",
            index=models.Index(
                fields=["recruiter", "scheduled_at"],
                name="interview_i_recruit_07c270_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interview",
            index=models.Index(
                fields=["status", "scheduled_at"], name="interview_i_status_c2c60a_idx"
            ),
        ),
    ]
