# Generated by Django 5.2.6 on 2025-09-12 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0002_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="interview",
            name="interview_i_company_3a464e_idx",
        ),
        migrations.RemoveField(
            model_name="interview",
            name="company",
        ),
        migrations.RemoveField(
            model_name="interview",
            name="feedback",
        ),
        migrations.RemoveField(
            model_name="interview",
            name="interview_team",
        ),
        migrations.RemoveField(
            model_name="interview",
            name="interview_type",
        ),
        migrations.RemoveField(
            model_name="interview",
            name="is_remote",
        ),
        migrations.RemoveField(
            model_name="interview",
            name="job",
        ),
        migrations.RemoveField(
            model_name="interview",
            name="location",
        ),
        migrations.RemoveField(
            model_name="interview",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="interview",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="interview",
            name="result",
        ),
        migrations.AlterField(
            model_name="interview",
            name="duration",
            field=models.IntegerField(
                default=60,
                help_text="Duration in minutes",
                validators=[
                    django.core.validators.MinValueValidator(15),
                    django.core.validators.MaxValueValidator(480),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
    ]
