# Generated by Django 5.2.6 on 2025-09-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIReport",
            fields=[
                ("report_id", models.AutoField(primary_key=True, serialize=False)),
                ("conversation_id", models.IntegerField()),
                (
                    "skill_match_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "final_match_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("strengths", models.TextField(blank=True, null=True)),
                ("weaknesses", models.TextField(blank=True, null=True)),
                ("overall_recommendation", models.TextField(blank=True, null=True)),
                (
                    "skills_breakdown",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "initial_analysis",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "performance_analysis",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
