# Generated by Django 5.2.6 on 2025-09-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIReport",
            fields=[
                ("report_id", models.AutoField(primary_key=True, serialize=False)),
                ("conversation", models.IntegerField()),
                (
                    "skill_match_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("strengths", models.TextField(blank=True, null=True)),
                ("weaknesses", models.TextField(blank=True, null=True)),
                ("overall_recommendation", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Report",
                "verbose_name_plural": "AI Reports",
                "db_table": "ai_reports",
            },
        ),
    ]
