# Generated by Django 5.2.6 on 2025-09-12 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_reports", "0001_initial"),
        ("interviewConversation", "0002_interviewconversation_interview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aireport",
            name="conversation_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="interviewConversation.interviewconversation",
            ),
        ),
    ]
