# Generated by Django 5.2.6 on 2025-09-14 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_reports", "0001_initial"),
        ("interviewConversation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aireport",
            name="conversation_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="interviewConversation.interviewconversation",
            ),
        ),
    ]
