# Generated by Django 4.2.24 on 2025-09-12 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_reports", "0001_initial"),
        ("interviewConversation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aireport",
            name="conversation_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="interviewConversation.interviewconversation",
            ),
        ),
    ]
