# Generated by Django 5.2.6 on 2025-09-10 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_reports", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aireport",
            old_name="conversation",
            new_name="conversation_id",
        ),
    ]
