# Generated by Django 5.2.6 on 2025-09-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_reports", "0002_rename_conversation_aireport_conversation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="aireport",
            name="final_match_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="aireport",
            name="initial_analysis",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="aireport",
            name="performance_analysis",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="aireport",
            name="skills_breakdown",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
