# Generated by Django 5.2.6 on 2025-09-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ai_reports",
            "0003_aireport_final_match_score_aireport_initial_analysis_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aireport",
            options={},
        ),
        migrations.AlterModelTable(
            name="aireport",
            table=None,
        ),
    ]
