# Generated by Django 4.2.24 on 2025-09-12 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("interview", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewConversation",
            fields=[
                (
                    "conversation_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("question_text", models.TextField()),
                ("expected_answer", models.TextField(blank=True, null=True)),
                ("candidate_answer", models.TextField(blank=True, null=True)),
                ("transcript_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="interview.interview",
                    ),
                ),
            ],
        ),
    ]
