# Generated by Django 5.2.6 on 2025-09-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InterviewConversation",
            fields=[
                (
                    "conversation_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("question_text", models.TextField()),
                ("expected_answer", models.TextField(blank=True, null=True)),
                ("candidate_answer", models.TextField(blank=True, null=True)),
                ("transcript_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
