# Generated by Django 4.2.24 on 2025-09-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interviewConversation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interviewconversation",
            name="updated_at",
        ),
    ]
