# Generated by Django 5.2.6 on 2025-09-12 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0003_remove_interview_interview_i_company_3a464e_idx_and_more"),
        ("interviewConversation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewconversation",
            name="interview",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="interview.interview",
            ),
            preserve_default=False,
        ),
    ]
