# Generated by Django 4.2.24 on 2025-09-14 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("companies", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="company",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="company",
            name="odoo_credentials",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.odoocredentials",
            ),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.UniqueConstraint(
                fields=("recruiter", "company_name"),
                name="unique_recruiter_company_name",
            ),
        ),
        migrations.RemoveField(
            model_name="company",
            name="odoo_company_id",
        ),
    ]
