# Generated by Django 4.2.24 on 2025-10-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_alter_company_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="odoo_company_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
