# Generated by Django 5.2.6 on 2025-09-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="odoo_company_id",
        ),
    ]