# Generated by Django 5.2.6 on 2025-09-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_remove_company_odoo_company_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="odoo_company_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
