# Generated by Django 4.2.24 on 2025-09-12 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                ("candidate_id", models.AutoField(primary_key=True, serialize=False)),
                ("odoo_candidate_id", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("generated_skill_summary", models.TextField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("qualified", "Qualified"),
                            ("interview", "Interview"),
                            ("offer", "Offer"),
                            ("hired", "Hired"),
                            ("rejected", "Rejected"),
                        ],
                        default="applied",
                        max_length=50,
                    ),
                ),
                ("partner_id", models.IntegerField(blank=True, null=True)),
                ("date_open", models.DateTimeField(blank=True, null=True)),
                ("date_last_stage_update", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CandidateAttachment",
            fields=[
                ("attachment_id", models.AutoField(primary_key=True, serialize=False)),
                ("odoo_attachment_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "original_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("file", models.FileField(upload_to="candidate_attachments/%Y/%m/%d/")),
                ("file_type", models.CharField(max_length=100)),
                ("file_size", models.IntegerField(default=0)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="candidate.candidate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
