# Generated by Django 4.2.24 on 2025-09-12 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidate", "0001_initial"),
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidates",
                to="job.job",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="candidate",
            unique_together={("job", "odoo_candidate_id")},
        ),
    ]
