# Generated by Django 5.2.6 on 2025-09-12 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidate", "0001_initial"),
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="job.job"
            ),
        ),
    ]
