# Generated by Django 5.2.6 on 2025-09-11 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidate", "0001_initial"),
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidates",
                to="job.job",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="candidate",
            unique_together={("job", "odoo_candidate_id")},
        ),
    ]
