# Generated by Django 5.2.6 on 2025-09-10 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='job',
            new_name='job_id',
        ),
    ]
