# Generated by Django 5.2.6 on 2025-09-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_rename_job_candidate_job_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='job_id',
            new_name='job',
        ),
    ]
