# Generated by Django 5.2.6 on 2025-09-11 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="phone",
        ),
    ]
