# Generated by Django 5.2.6 on 2025-09-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0003_remove_candidate_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
