# Generated by Django 4.2.24 on 2025-10-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0003_alter_candidateattachment_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateattachment",
            name="file",
            field=models.FileField(upload_to="candidate_attachments/%Y/%m/%d/"),
        ),
    ]
