# Generated by Django 5.2.6 on 2025-09-12 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0004_candidate_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateAttachment",
            fields=[
                ("attachment_id", models.AutoField(primary_key=True, serialize=False)),
                ("odoo_attachment_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "original_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("file", models.FileField(upload_to="candidate_attachments/%Y/%m/%d/")),
                ("file_type", models.CharField(max_length=100)),
                ("file_size", models.IntegerField(default=0)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="candidate.candidate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
