# Generated by Django 4.2.24 on 2025-09-12 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("job_id", models.AutoField(primary_key=True, serialize=False)),
                ("odoo_job_id", models.IntegerField(blank=True, null=True)),
                ("job_title", models.CharField(max_length=100)),
                ("job_description", models.TextField()),
                ("generated_job_summary", models.TextField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("recruit", "Recruitment in Progress"),
                            ("pause", "Paused"),
                            ("close", "Closed"),
                            ("cancel", "Cancelled"),
                        ],
                        default="open",
                        max_length=50,
                    ),
                ),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "odoo_job_id")},
            },
        ),
    ]
