# Generated by Django 4.2.24 on 2025-09-12 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0002_job_is_active_job_odoo_job_id_job_recruiter_and_more"),
        ("job", "0002_job_updated_at"),
    ]

    operations = []
