# Generated by Django 4.2.24 on 2025-09-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0002_alter_job_unique_together_alter_job_expired_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="expired_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
