# Generated by Django 4.2.24 on 2025-09-12 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_company_odoo_company_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("job", "0003_merge_20250912_1157"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="job",
            unique_together={("company", "odoo_job_id")},
        ),
        migrations.AlterField(
            model_name="job",
            name="recruiter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs_recruited",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
