# Generated by Django 4.2.24 on 2025-09-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0003_alter_job_expired_at"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="job",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="job",
            name="expired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="job",
            name="odoo_job_id",
        ),
    ]
