# Generated by Django 4.2.24 on 2025-09-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0004_alter_job_unique_together_alter_job_expired_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="posted_at",
            field=models.DateTimeField(),
        ),
    ]
