# Generated by Django 4.2.24 on 2025-10-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0005_alter_job_posted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="odoo_job_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
