# Generated by Django 4.2.24 on 2025-11-04 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_company_odoo_company_id"),
        ("job", "0006_job_odoo_job_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="job",
            unique_together={("company", "odoo_job_id")},
        ),
    ]
